# Data Collection

## Popular Techniques

- Public Datasets : Kaggle, UCI ML Repo etc.
- Databses : SQLAIchemy, sqlite3, PyMySWL, pymongo, py2neo etc.
- APIs : retrieve structured data (JSON/XML etc.)
- Web Scraping - BeautifulSoup, lxml, Selenium, Playwrigth etc.

## API's
uses HTTP requests

# Working with APIs  --> application Programming Interface
## using requests

In [1]:
!pip install requests

Requirement already satisfied: requests in a:\anaconda\lib\site-packages (2.33.0)
Requirement already satisfied: charset_normalizer<4,>=2 in a:\anaconda\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in a:\anaconda\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in a:\anaconda\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in a:\anaconda\lib\site-packages (from requests) (2026.1.4)

In [2]:
# Stephen Kind (REST APIs)

# requests types -> get,post

In [16]:
import requests

URL = "https://dattebayo-api.onrender.com/tailed-beasts"

res = requests.get(URL)

In [17]:
res
# 200 is status code
# 404 page not found
# 500 internal server error
json_data = res.json()

In [18]:
json_data

{'tailed-beasts': [{'id': 1,
   'name': 'Ten-Tails',
   'images': ['https://static.wikia.nocookie.net/naruto/images/e/e6/Ten-Tails_emerges.png'],
   'debut': {'manga': 'Naruto Chapter #467',
    'anime': 'Naruto Shippūden Episode #205',
    'novel': 'The Last: Naruto the Movie',
    'movie': 'The Last: Naruto the Movie',
    'game': 'Naruto Shippūden: Ultimate Ninja Storm Revolution',
    'ova': 'The Far Reaches of Hope',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'incarnation with the god tree': 'Kaguya Ōtsutsuki',
    'depowered form': 'Demonic Statue of the Outer Path'},
   'jutsu': ['Six Paths Senjutsu',
    'Tailed Beast Ball',
    'Tailed Beast Chakra Arms',
    'Tailed Beast Shockwave',
    'Ten-Tails Fission',
    'Tenpenchii',
    'Truth-Seeking Ball',
    'Wood Release: Cutting Technique'],
   'natureType': ['Fire Release',
    'Wind Release',
    'Lightning Release',
    'Earth Release',
    'Water Release',
    'Wood Release',
    'Yin Release',
    'Yang Release',
    'Yin–Yang Release'],
   'personal': {'status': 'Incapacitated',
    'kekkeiGenkai': 'Wood Release',
    'classification': 'Tailed Beast',
    'jinchūriki': ['Hagoromo Ōtsutsuki', 'Obito Uchiha', 'Madara Uchiha'],
    'titles': ['十尾Jūbi',
     'one-eyedGod(天目一箇神,AmeNoHitotsuNoKami)',
     'datara(ダタラ)',
     'deidarabotchi(デイダラボッチ,Deidarabocchi)',
     'nation-buildingGod(国造りの神,KunizukuriNoKami)']},
   'uniqueTraits': ['Can absorb chakra']},
  {'id': 153,
   'name': 'Chōmei',
   'images': ['https://static.wikia.nocookie.net/naruto/images/7/78/Chomei.png'],
   'debut': {'manga': 'Naruto Chapter #467',
    'anime': 'Naruto Shippūden Episode #165',
    'novel': 'The Last: Naruto the Movie',
    'movie': 'The Last: Naruto the Movie',
    'game': 'Naruto Shippūden: Ultimate Ninja Storm 3',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'creator': 'Hagoromo Ōtsutsuki', 'sibling': 'Kurama'},
   'jutsu': ['Bug Bite',
    'Chakra Transfer Technique',
    'Cocoon (Anime only)',
    'Spear Attack Shining Horn',
    'Tailed Beast Ball',
    'Tailed Beast Full Charge',
    'Tailed Beast Telepathy'],
   'personal': {'species': 'Kabutomushi',
    'classification': 'Tailed Beast',
    'jinchūriki': ['Fū', 'Naruto Uzumaki'],
    'affiliation': 'Takigakure'},
   'voiceActors': {'japanese': 'Kenichi Suzumura', 'english': 'Steven Blum'}},
  {'id': 345,
   'name': 'Gyūki',
   'images': ['https://static.wikia.nocookie.net/naruto/images/d/d7/Gyuki.png'],
   'debut': {'manga': 'Naruto Chapter #413',
    'anime': 'Naruto Shippūden Episode #143',
    'novel': 'The Last: Naruto the Movie',
    'movie': 'Naruto the Movie: Blood Prison',
    'game': 'Naruto Shippūden: Ultimate Ninja Storm 2',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'creator': 'Hagoromo Ōtsutsuki', 'sibling': 'Kurama'},
   'jutsu': ['The Springtime of Youth wiki has an article about this topic:',
    'Eight-Tails'],
   'personal': {'species': 'Ushi-oni',
    'classification': 'Tailed Beast',
    'jinchūriki': ['Blue B', 'Killer B', 'Obito Uchiha', 'Naruto Uzumaki'],
    'affiliation': ['Kumogakure', 'Allied Shinobi Forces']},
   'uniqueTraits': ['Produces ink'],
   'voiceActors': {'japanese': 'Masaki Aizawa',
    'english': ['Matthew Mercer',
     'Fred Tatasciore   (Naruto Shippūden: Ultimate Ninja Storm 3)']}},
  {'id': 480,
   'name': 'Isobu',
   'images': ['https://static.wikia.nocookie.net/naruto/images/d/df/Isobu.png'],
   'debut': {'manga': 'Naruto Chapter #317',
    'anime': 'Naruto Shippūden Episode #92',
    'novel': 'The Last: Naruto the Movie',
    'movie': 'The Last: Naruto the Movie',
    'game': 'Naruto Shippūden: Ninja Destiny 3',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'creator': 'Hagoromo Ōtsutsuki', 'sibling': 'Kurama'},
   'jutsu': ['Chakra Transfer Technique',
    'Coral Palm',
    'Illusionary Mist (Anime only)',
    'Leaping Bullet Shell Tower',
    'Shadow Stroke',
    'Tailed Beast Ball',
    'Tailed Beast Full Charge',
    'Tailed Beast Shockwave (Anime only)',
    'Tailed Beast Telepathy',
    'Three-Tails Mini Clone (Anime only)',
    'Water Release: Great Water Mass Bullet (Anime only)'],
   'natureType': ['Water Release', 'Yin Release  (Anime only)'],
   'personal': {'species': 'Turtle',
    'classification': 'Tailed Beast',
    'jinchūriki': ['Rin Nohara', 'Yagura Karatachi', 'Naruto Uzumaki'],
    'affiliation': 'Kirigakure'},
   'uniqueTraits': ['Produces Coral'],
   'voiceActors': {'japanese': 'Shigenori Sōya', 'english': 'Chris Edgerly'}},
  {'id': 669,
   'name': 'Kokuō',
   'images': ['https://static.wikia.nocookie.net/naruto/images/a/a3/Kokuo.png'],
   'debut': {'manga': 'Naruto Chapter #467',
    'anime': 'Naruto Shippūden Episode #165',
    'novel': 'The Last: Naruto the Movie',
    'movie': 'The Last: Naruto the Movie',
    'game': 'Naruto Shippūden: Ultimate Ninja Storm 3',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'creator': 'Hagoromo Ōtsutsuki', 'sibling': 'Kurama'},
   'jutsu': ['Boil Release: Unrivalled Strength',
    'Chakra Transfer Technique',
    'Horn Breaking',
    'Tailed Beast Ball',
    'Tailed Beast Chakra Arms',
    'Tailed Beast Full Charge',
    'Tailed Beast Telepathy'],
   'natureType': ['Boil Release', 'Fire Release', 'Water Release'],
   'personal': {'kekkeiGenkai': 'Boil Release',
    'classification': 'Tailed Beast',
    'jinchūriki': ['Han', 'Naruto Uzumaki'],
    'affiliation': 'Iwagakure'},
   'voiceActors': {'japanese': 'Mie Sonozaki',
    'english': 'Mary Elizabeth McGlynn'}},
  {'id': 711,
   'name': 'Kurama',
   'images': [],
   'debut': {'manga': 'Naruto Chapter #1',
    'anime': 'Naruto Episode #1',
    'novel': 'Naruto: Innocent Heart, Demonic Blood',
    'movie': 'Naruto the Movie: Ninja Clash in the Land of Snow',
    'game': 'Naruto: Konoha Ninpōchō',
    'ova': 'Naruto Shippūden: UNSG anime cutscenes',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'creator': 'Hagoromo Ōtsutsuki', 'sibling': 'Gyūki'},
   'jutsu': ['The Springtime of Youth wiki has an article about this topic:',
    'Nine-Tails'],
   'natureType': ['Fire Release  (Anime only)', 'Wind Release  (Anime only)'],
   'personal': {'species': 'Kitsune',
    'status': 'Deceased',
    'classification': ['Tailed Beast', 'Sensor Type', 'Sage'],
    'jinchūriki': ['Mito Uzumaki',
     'Kushina Uzumaki',
     'Minato Namikaze (Yin half)',
     'Naruto Uzumaki',
     'Black Zetsu (Yin half)',
     'Obito Uchiha (Yin half)'],
    'affiliation': ['Konohagakure', 'Allied Shinobi Forces'],
    'titles': ['九喇嘛Kurama',
     'nine-tails(九尾,Kyūbi)',
     'nine-tailedDemonFox(九尾の妖狐,KyūbiNoYōko,EnglishTv:Nine-tailedFox)',
     'monsterFox(化け狐',
     'バケ狐,Bakegitsune)']},
   'uniqueTraits': ['Detects negative emotions'],
   'voiceActors': {'japanese': 'Tesshō Genda', 'english': 'Paul St. Peter'}},
  {'id': 771,
   'name': 'Matatabi',
   'images': ['https://static.wikia.nocookie.net/naruto/images/a/a7/Matatabi.png'],
   'debut': {'manga': 'Naruto Chapter #313',
    'anime': 'Naruto Shippūden Episode #72',
    'novel': 'The Last: Naruto the Movie',
    'movie': 'The Last: Naruto the Movie',
    'game': 'Naruto Shippūden: Ninja Destiny 3',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'creator': 'Hagoromo Ōtsutsuki', 'sibling': 'Kurama'},
   'jutsu': ['<a href="/wiki/File:Nibi_mural.png" title="File:Nibi mural.png"><img alt="" src="https://static.wikia.nocookie.net/naruto/images/0/0a/Nibi_mural.png/revision/latest/scale-to-width-down/180?cb=20210805003640" decoding="async" loading="lazy" width="180" height="101" class="thumbimage" data-image-name="Nibi mural.png" data-image-key="Nibi_mural.png" data-src="https://static.wikia.nocookie.net/naruto/images/0/0a/Nibi_mural.png/revision/latest/scale-to-width-down/180?cb=20210805003640" /></a> \t \t\t \t\t \t\t \t\t\tMatatabi\'s wall mural inside the Falls of Truth.'],
   'natureType': ['Fire Release'],
   'personal': {'species': 'Bakeneko',
    'classification': 'Tailed Beast',
    'jinchūriki': ['Yugito Nii', 'Naruto Uzumaki'],
    'affiliation': 'Kumogakure'},
   'uniqueTraits': ['Produce blue flames'],
   'voiceActors': {'japanese': 'Ryōko Shiraishi', 'english': 'Cristina Vee'}},
  {'id': 1009,
   'name': 'Saiken',
   'images': ['https://static.wikia.nocookie.net/naruto/images/5/58/Saiken.png'],
   'debut': {'manga': 'Naruto Chapter #467',
    'anime': 'Naruto Shippūden Episode #151',
    'novel': 'The Last: Naruto the Movie',
    'movie': 'The Last: Naruto the Movie',
    'game': 'Naruto Shippūden: Ultimate Ninja Storm 3',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'creator': 'Hagoromo Ōtsutsuki', 'sibling': 'Kurama'},
   'jutsu': ['Chakra Transfer Technique',
    'Leech Gap',
    'Soap Bubble Ninjutsu (Anime only)',
    'Tailed Beast Ball',
    'Tailed Beast Full Charge',
    'Tailed Beast Telepathy',
    'Water Release: Starch Syrup Capturing Field',
    'Wisdom Wolf Decay'],
   'natureType': ['Water Release'],
   'personal': {'species': 'Slug',
    'classification': 'Tailed Beast',
    'jinchūriki': ['Utakata', 'Naruto Uzumaki'],
    'affiliation': 'Kirigakure'},
   'uniqueTraits': ['Secretes corrosive alkali'],
   'voiceActors': {'japanese': 'Miyu Irino', 'english': 'Todd Haberkorn'}},
  {'id': 1127,
   'name': 'Shukaku',
   'images': ['https://static.wikia.nocookie.net/naruto/images/9/99/Shukaku.png'],
   'debut': {'manga': 'Naruto Chapter #134',
    'anime': 'Naruto Episode #78',
    'novel': 'The Last: Naruto the Movie',
    'movie': 'The Last: Naruto the Movie',
    'game': 'Naruto: Ultimate Ninja',
    'ova': 'Naruto x UT',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'creator': 'Hagoromo Ōtsutsuki', 'sibling': 'Kurama'},
   'jutsu': ['Chakra Transfer Technique',
    'Desert Layered Imperial Funeral Seal',
    'Tailed Beast Ball',
    'Tailed Beast Full Charge',
    'Tailed Beast Shockwave (Anime only)',
    'Tailed Beast Telepathy',
    'Wind Release: Drilling Air Bullet',
    'Wind Release: Sand Buckshot'],
   'natureType': ['Magnet Release', 'Wind Release', 'Earth Release'],
   'personal': {'species': 'Tanuki',
    'kekkeiGenkai': 'Magnet Release',
    'classification': 'Tailed Beast',
    'jinchūriki': ['Bunpuku', 'Gaara', 'Obito Uchiha', 'Naruto Uzumaki'],
    'affiliation': 'Sunagakure'},
   'tools': ['Sand'],
   'uniqueTraits': ['Manipulates sand',
    'Influences its sleeping jinchūriki',
    'Natural cursed seal markings'],
   'voiceActors': {'japanese': 'Hiroshi Iwasaki',
    'english': ['Kirk Thornton', "Liam O'Brien   (Video games)"]}},
  {'id': 1134,
   'name': 'Son Gokū',
   'images': ['https://static.wikia.nocookie.net/naruto/images/5/5e/Son_Goku.png'],
   'debut': {'manga': 'Naruto Chapter #467',
    'anime': 'Naruto Shippūden Episode #165',
    'novel': 'The Last: Naruto the Movie',
    'movie': 'The Last: Naruto the Movie',
    'game': 'Naruto Shippūden: Ultimate Ninja Storm 3',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'creator': 'Hagoromo Ōtsutsuki', 'sibling': 'Kurama'},
   'jutsu': ['Chakra Transfer Technique',
    'Flower–Fruit Mountain',
    'Monkey Flame Arson',
    'Tailed Beast Ball',
    'Tailed Beast Full Charge',
    'Tailed Beast Telepathy'],
   'natureType': ['Lava Release', 'Fire Release', 'Earth Release'],
   'personal': {'species': 'Monkey',
    'kekkeiGenkai': 'Lava Release',
    'classification': ['Tailed Beast', 'Sage'],
    'jinchūriki': ['Rōshi', 'Naruto Uzumaki'],
    'affiliation': 'Iwagakure'},
   'voiceActors': {'japanese': 'Hiroki Yasumoto',
    'english': 'John Eric Bentley'}}],
 'currentPage': 1,
 'pageSize': 20,
 'total': 10}

In [20]:
import pandas as pd

df = pd.json_normalize(json_data["tailed-beasts"])

In [21]:
df

,id,name,images,jutsu,natureType,uniqueTraits,debut.manga,debut.anime,debut.novel,debut.movie,...,personal.classification,personal.jinchūriki,personal.titles,family.creator,family.sibling,personal.species,personal.affiliation,voiceActors.japanese,voiceActors.english,tools
0,1,Ten-Tails,[https://static.wikia.nocookie.net/naruto/imag...,"[Six Paths Senjutsu, Tailed Beast Ball, Tailed...","[Fire Release, Wind Release, Lightning Release...",[Can absorb chakra],Naruto Chapter #467,Naruto Shippūden Episode #205,The Last: Naruto the Movie,The Last: Naruto the Movie,...,Tailed Beast,"[Hagoromo Ōtsutsuki, Obito Uchiha, Madara Uchiha]","[十尾Jūbi, one-eyedGod(天目一箇神,AmeNoHitotsuNoKami)...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,153,Chōmei,[https://static.wikia.nocookie.net/naruto/imag...,"[Bug Bite, Chakra Transfer Technique, Cocoon (...",NaN,NaN,Naruto Chapter #467,Naruto Shippūden Episode #165,The Last: Naruto the Movie,The Last: Naruto the Movie,...,Tailed Beast,"[Fū, Naruto Uzumaki]",NaN,Hagoromo Ōtsutsuki,Kurama,Kabutomushi,Takigakure,Kenichi Suzumura,Steven Blum,NaN
2,345,Gyūki,[https://static.wikia.nocookie.net/naruto/imag...,[The Springtime of Youth wiki has an article a...,NaN,[Produces ink],Naruto Chapter #413,Naruto Shippūden Episode #143,The Last: Naruto the Movie,Naruto the Movie: Blood Prison,...,Tailed Beast,"[Blue B, Killer B, Obito Uchiha, Naruto Uzumaki]",NaN,Hagoromo Ōtsutsuki,Kurama,Ushi-oni,"[Kumogakure, Allied Shinobi Forces]",Masaki Aizawa,"[Matthew Mercer, Fred Tatasciore (Naruto Shi...",NaN
3,480,Isobu,[https://static.wikia.nocookie.net/naruto/imag...,"[Chakra Transfer Technique, Coral Palm, Illusi...","[Water Release, Yin Release (Anime only)]",[Produces Coral],Naruto Chapter #317,Naruto Shippūden Episode #92,The Last: Naruto the Movie,The Last: Naruto the Movie,...,Tailed Beast,"[Rin Nohara, Yagura Karatachi, Naruto Uzumaki]",NaN,Hagoromo Ōtsutsuki,Kurama,Turtle,Kirigakure,Shigenori Sōya,Chris Edgerly,NaN
4,669,Kokuō,[https://static.wikia.nocookie.net/naruto/imag...,"[Boil Release: Unrivalled Strength, Chakra Tra...","[Boil Release, Fire Release, Water Release]",NaN,Naruto Chapter #467,Naruto Shippūden Episode #165,The Last: Naruto the Movie,The Last: Naruto the Movie,...,Tailed Beast,"[Han, Naruto Uzumaki]",NaN,Hagoromo Ōtsutsuki,Kurama,NaN,Iwagakure,Mie Sonozaki,Mary Elizabeth McGlynn,NaN
5,711,Kurama,[],[The Springtime of Youth wiki has an article a...,"[Fire Release (Anime only), Wind Release (An...",[Detects negative emotions],Naruto Chapter #1,Naruto Episode #1,"Naruto: Innocent Heart, Demonic Blood",Naruto the Movie: Ninja Clash in the Land of Snow,...,"[Tailed Beast, Sensor Type, Sage]","[Mito Uzumaki, Kushina Uzumaki, Minato Namikaz...","[九喇嘛Kurama, nine-tails(九尾,Kyūbi), nine-tailedD...",Hagoromo Ōtsutsuki,Gyūki,Kitsune,"[Konohagakure, Allied Shinobi Forces]",Tesshō Genda,Paul St. Peter,NaN
6,771,Matatabi,[https://static.wikia.nocookie.net/naruto/imag...,"[<a href=""/wiki/File:Nibi_mural.png"" title=""Fi...",[Fire Release],[Produce blue flames],Naruto Chapter #313,Naruto Shippūden Episode #72,The Last: Naruto the Movie,The Last: Naruto the Movie,...,Tailed Beast,"[Yugito Nii, Naruto Uzumaki]",NaN,Hagoromo Ōtsutsuki,Kurama,Bakeneko,Kumogakure,Ryōko Shiraishi,Cristina Vee,NaN
7,1009,Saiken,[https://static.wikia.nocookie.net/naruto/imag...,"[Chakra Transfer Technique, Leech Gap, Soap Bu...",[Water Release],[Secretes corrosive alkali],Naruto Chapter #467,Naruto Shippūden Episode #151,The Last: Naruto the Movie,The Last: Naruto the Movie,...,Tailed Beast,"[Utakata, Naruto Uzumaki]",NaN,Hagoromo Ōtsutsuki,Kurama,Slug,Kirigakure,Miyu Irino,Todd Haberkorn,NaN
8,1127,Shukaku,[https://static.wikia.nocookie.net/naruto/imag...,"[Chakra Transfer Technique, Desert Layered Imp...","[Magnet Release, Wind Release, Earth Release]","[Manipulates sand, Influences its sleeping jin...",Naruto Chapter #134,Naruto Episode #78,The Last: Naruto the Movie,The Last: Naruto the Movie,...,Tailed Beast,"[Bunpuku, Gaara, Obito Uchiha, Naruto Uzumaki]",NaN,Hagoromo Ōtsutsuki,Kurama,Tanuki,Sunagakure,Hiroshi Iwasaki,"[Kirk Thornton, Liam O'Brien (Video games)]",[Sand]
9,1134,Son Gokū,[https://static.wikia.nocookie.net/naruto/imag...,"[Chakra Transfer Technique, Flower–Fruit Mount...","[Lava Release, Fire Release, Earth Release]",NaN,Naruto Chapter #467,Naruto Shippūden Episode #165,The Last: Naruto the Movie,The Last: Naruto the Movie,...,"[Tailed Beast, Sage]","[Rōshi, Naruto Uzumaki]",NaN,Hagoromo Ōtsutsuki,Kurama,Monkey,Iwagakure,Hiroki Yasumoto,John Eric Bentley,NaN

In [25]:
df.columns
df = df[['id','name','jutsu','natureType']]

In [26]:
df

,id,name,jutsu,natureType
0,1,Ten-Tails,"[Six Paths Senjutsu, Tailed Beast Ball, Tailed...","[Fire Release, Wind Release, Lightning Release..."
1,153,Chōmei,"[Bug Bite, Chakra Transfer Technique, Cocoon (...",NaN
2,345,Gyūki,[The Springtime of Youth wiki has an article a...,NaN
3,480,Isobu,"[Chakra Transfer Technique, Coral Palm, Illusi...","[Water Release, Yin Release (Anime only)]"
4,669,Kokuō,"[Boil Release: Unrivalled Strength, Chakra Tra...","[Boil Release, Fire Release, Water Release]"
5,711,Kurama,[The Springtime of Youth wiki has an article a...,"[Fire Release (Anime only), Wind Release (An..."
6,771,Matatabi,"[<a href=""/wiki/File:Nibi_mural.png"" title=""Fi...",[Fire Release]
7,1009,Saiken,"[Chakra Transfer Technique, Leech Gap, Soap Bu...",[Water Release]
8,1127,Shukaku,"[Chakra Transfer Technique, Desert Layered Imp...","[Magnet Release, Wind Release, Earth Release]"
9,1134,Son Gokū,"[Chakra Transfer Technique, Flower–Fruit Mount...","[Lava Release, Fire Release, Earth Release]"