In [160]:
!pip install pandas

Requirement already satisfied: pandas in a:\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in a:\anaconda\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in a:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in a:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in a:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in a:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [161]:
import pandas as pd

In [162]:
info = {
    "Name": ["Rahul","Harshita","Shradha"],
    "CGPA": [9.5,7.5,8.5,]
}

df = pd.DataFrame(info)

In [163]:
print(df)

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2   Shradha   8.5

In [164]:
df

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2   Shradha   8.5

In [165]:
# Series

s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [166]:
type(s)

pandas.core.series.Series

In [167]:
# index

print(s[0])
print(s[2])

1
3

In [168]:
s = pd.Series([21,24,25,26], index=["Adam","Eve","Bob","Charlie"])

In [169]:
print(s)

Adam       21
Eve        24
Bob        25
Charlie    26
dtype: int64

In [170]:
print(s["Adam"])

21

In [171]:
print(s["Bob"])

25

In [172]:
print(s[3])

26

C:\Users\venka\AppData\Local\Temp\ipykernel_9660\3567120435.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[3])

In [173]:
print(s.index)

Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='object')

In [174]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1+s2)
s1[0] = 100
print(s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [175]:
changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [176]:
# DataFrame

info = {
    "Name": ["Adam","Eve","Bob"],
    "Age":[23,24,25],
    "GPA":[9.5,8.6,7.2]
}

df = pd.DataFrame(info)

print(df, type(df))

   Name  Age  GPA
0  Adam   23  9.5
1   Eve   24  8.6
2   Bob   25  7.2 <class 'pandas.core.frame.DataFrame'>

In [177]:
df

   Name  Age  GPA
0  Adam   23  9.5
1   Eve   24  8.6
2   Bob   25  7.2

In [178]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [179]:
df = pd.DataFrame([["Adam",23],["Bob",24],["Eve",23]],columns=["Name","Age"])
print(df)

   Name  Age
0  Adam   23
1   Bob   24
2   Eve   23

In [180]:
import numpy as np

np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr,columns=["A","B","C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [181]:
# csv data
df = pd.read_csv("employee_data.csv")
print(df)
print(type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.core.frame.DataFrame'>

In [182]:
# json data

df = pd.read_json("employee_data.json")
print(df)
print(type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.core.frame.DataFrame'>

In [183]:
# excel
pd.read_excel()

# sql
pd.read_sql()

TypeError: read_excel() missing 1 required positional argument: 'io'

In [ ]:
# Methods

(df.head()) # starting 5 rows

df.tail() # last 5 rows

df.tail(2)

df.sample() # random
df.sample(6)


# df.info() # information like (type,range,columns)


df.shape


df.describe() # give important insights

df.columns


df.nunique()

In [ ]:
df

In [ ]:
# AQI Data set

df = pd.read_csv("globalAirQuality.csv")

df

In [ ]:
df.describe()

In [ ]:
df

In [ ]:
# selecting date

#columns
df["city"]
df[["city","aqi"]]  # columns names are case sensitive


#rows
df.loc[2]
df.loc[0:2]  # start idx : end idx [inclusive]


df.iloc[2]
df.iloc[0:3] # end idx exclusive


df.loc[0:2,["city","aqi"]]
df.iloc[0:3,[1,2,3,4]] #position
df.iloc[0:3,1:5]


# single scalar values (at & iat)

df.at[0,"city"]
df.iat[0,2]


df["city"]   # view, not copy

cities = df["city"]
cities[0] = "New York"
df


# copy

cities = df["city"].copy()
cities[0] = "Mumbai"

df
cities

In [ ]:
# Filtering of Data

df[ (df["aqi"] > 100) & (df["temperature"] > 30) ]
df[ (df["aqi"] > 100) & (df["temperature"] < 30) ]


aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30) ][["city","aqi"]]

aqi_data
aqi_data.iloc[0]
aqi_data.loc[6]

In [ ]:
# filtering data using query

# Query
df.query("aqi>100")

# Rules
# 1. Expressed as a string
# 2. Column based reference
# 3. Backticks for col_name with space or special chars
# 4. Operators (&, |, ~, >=, >, <=, <, == etc.)
# 5. @ to reference Python vars
# 6. Chained comparisons

df.query("aqi>100 & temperature > 30")[["city","aqi"]]


aqi_val = 100
df.query("aqi > @aqi_val & temperature > 30")[["city","aqi"]]


# query returns copy. not view.

In [185]:
# Data Cleaning

# Handle Missing Values.

# - isnull()                #NaN -> Not a Null
# - isnull() / isna() (alias)  ->roots in R
# - isnull().sum()
# - dropna()
# - fillna(value)
# - ffill()
# - bfill()


df = pd.read_csv("raw_data.csv")

In [186]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [187]:
df.isnull()
df.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [188]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [189]:
df.dropna() #rows

df.dropna(axis=1)

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [190]:
df.fillna(0)
df.fillna(100)

age_mean = df["age"].mean()

cleaned_data = df.copy()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

In [191]:
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [192]:

# ffill() ---> forward fill

df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [193]:
# bfill() --> backward fill

df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [194]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [195]:
# Handle Duplicate Values

# duplicated()
# drop_duplicates()


df.duplicated()
df["country"].duplicated()
df[["country","gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [196]:
df2 = df.copy()

df.drop_duplicates(inplace=True)

In [197]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [198]:
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Handle Data Types & date-time

In [199]:
# dtypes
# astype( newType )
# to_datetime()

In [200]:
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [204]:
df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [205]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [206]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [212]:
date_str = "2026-12-31"
type(date_str)

date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [221]:
date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [ ]:
# Handle Strings

.str.lower() ,