In [1]:
!pip install pandas

Requirement already satisfied: pandas in a:\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in a:\anaconda\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in a:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in a:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in a:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in a:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
info = {
    "Name": ["Rahul","Harshita","Shradha"],
    "CGPA": [9.5,7.5,8.5,]
}

df = pd.DataFrame(info)

In [4]:
print(df)

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2   Shradha   8.5

In [5]:
df

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2   Shradha   8.5

In [6]:
# Series

s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
type(s)

pandas.core.series.Series

In [8]:
# index

print(s[0])
print(s[2])

1
3

In [9]:
s = pd.Series([21,24,25,26], index=["Adam","Eve","Bob","Charlie"])

In [10]:
print(s)

Adam       21
Eve        24
Bob        25
Charlie    26
dtype: int64

In [11]:
print(s["Adam"])

21

In [12]:
print(s["Bob"])

25

In [13]:
print(s[3])

26

C:\Users\venka\AppData\Local\Temp\ipykernel_7912\3567120435.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[3])

In [14]:
print(s.index)

Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='object')

In [15]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1+s2)
s1[0] = 100
print(s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [16]:
changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [17]:
# DataFrame

info = {
    "Name": ["Adam","Eve","Bob"],
    "Age":[23,24,25],
    "GPA":[9.5,8.6,7.2]
}

df = pd.DataFrame(info)

print(df, type(df))

   Name  Age  GPA
0  Adam   23  9.5
1   Eve   24  8.6
2   Bob   25  7.2 <class 'pandas.core.frame.DataFrame'>

In [18]:
df

   Name  Age  GPA
0  Adam   23  9.5
1   Eve   24  8.6
2   Bob   25  7.2

In [19]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [20]:
df = pd.DataFrame([["Adam",23],["Bob",24],["Eve",23]],columns=["Name","Age"])
print(df)

   Name  Age
0  Adam   23
1   Bob   24
2   Eve   23

In [21]:
import numpy as np

np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr,columns=["A","B","C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [22]:
# csv data
df = pd.read_csv("employee_data.csv")
print(df)
print(type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.core.frame.DataFrame'>

In [23]:
# json data

df = pd.read_json("employee_data.json")
print(df)
print(type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000
<class 'pandas.core.frame.DataFrame'>

In [24]:
# excel
pd.read_excel()

# sql
pd.read_sql()

TypeError: read_excel() missing 1 required positional argument: 'io'

In [ ]:
# Methods

(df.head()) # starting 5 rows

df.tail() # last 5 rows

df.tail(2)

df.sample() # random
df.sample(6)


# df.info() # information like (type,range,columns)


df.shape


df.describe() # give important insights

df.columns


df.nunique()

In [ ]:
df

In [ ]:
# AQI Data set

df = pd.read_csv("globalAirQuality.csv")

df

In [ ]:
df.describe()

In [ ]:
df

In [ ]:
# selecting date

#columns
df["city"]
df[["city","aqi"]]  # columns names are case sensitive


#rows
df.loc[2]
df.loc[0:2]  # start idx : end idx [inclusive]


df.iloc[2]
df.iloc[0:3] # end idx exclusive


df.loc[0:2,["city","aqi"]]
df.iloc[0:3,[1,2,3,4]] #position
df.iloc[0:3,1:5]


# single scalar values (at & iat)

df.at[0,"city"]
df.iat[0,2]


df["city"]   # view, not copy

cities = df["city"]
cities[0] = "New York"
df


# copy

cities = df["city"].copy()
cities[0] = "Mumbai"

df
cities

In [ ]:
# Filtering of Data

df[ (df["aqi"] > 100) & (df["temperature"] > 30) ]
df[ (df["aqi"] > 100) & (df["temperature"] < 30) ]


aqi_data = df[ (df["aqi"] > 100) & (df["temperature"] > 30) ][["city","aqi"]]

aqi_data
aqi_data.iloc[0]
aqi_data.loc[6]

In [ ]:
# filtering data using query

# Query
df.query("aqi>100")

# Rules
# 1. Expressed as a string
# 2. Column based reference
# 3. Backticks for col_name with space or special chars
# 4. Operators (&, |, ~, >=, >, <=, <, == etc.)
# 5. @ to reference Python vars
# 6. Chained comparisons

df.query("aqi>100 & temperature > 30")[["city","aqi"]]


aqi_val = 100
df.query("aqi > @aqi_val & temperature > 30")[["city","aqi"]]


# query returns copy. not view.

In [ ]:
# Data Cleaning

# Handle Missing Values.

# - isnull()                #NaN -> Not a Null
# - isnull() / isna() (alias)  ->roots in R
# - isnull().sum()
# - dropna()
# - fillna(value)
# - ffill()
# - bfill()


df = pd.read_csv("raw_data.csv")

In [ ]:
df

In [ ]:
df.isnull()
df.isna()

In [ ]:
df.isnull().sum()

In [ ]:
df.dropna() #rows

df.dropna(axis=1)

In [ ]:
df.fillna(0)
df.fillna(100)

age_mean = df["age"].mean()

cleaned_data = df.copy()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)

In [ ]:
cleaned_data

In [ ]:

# ffill() ---> forward fill

df.ffill()

In [ ]:
# bfill() --> backward fill

df.bfill()

In [ ]:
df

In [ ]:
# Handle Duplicate Values

# duplicated()
# drop_duplicates()


df.duplicated()
df["country"].duplicated()
df[["country","gender"]].duplicated()

In [ ]:
df2 = df.copy()

df.drop_duplicates(inplace=True)

In [ ]:
df

In [ ]:
df2

## Handle Data Types & date-time

In [ ]:
# dtypes
# astype( newType )
# to_datetime()

In [ ]:
df.dtypes

In [ ]:
df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

In [ ]:
df2

In [ ]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data

In [ ]:
date_str = "2026-12-31"
type(date_str)

date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

In [ ]:
date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

In [ ]:
# Handle Strings

.str.lower()

In [ ]:
df